services:
  frontend:
    build:
      context: ./frontend
      args:
        - BACKEND_ADDR=http://${HOSTNAME}:${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:80"

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - FRONTEND_ADDR=http://${HOSTNAME}:${FRONTEND_PORT}
    volumes:
      - ./data:/usr/local/data
