services:
  frontend:
    build:
      context: ./frontend
      args:
        - BACKEND_ADDR=http://${HOSTNAME}:${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:80"

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - FRONTEND_ADDR=http://${HOSTNAME}:${FRONTEND_PORT}
      - BACKEND_PORT
      - DATABASE_ADDR=postgres://postgres:${DATABASE_PASSWORD}@database
    volumes:
      - ./data:/usr/local/data

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data/init:/docker-entrypoint-initdb.d

volumes:
  db_data:
